name: MQTT LoRa Autodiscovery Extended
version: 2.0.1
slug: mqtt_lora
description: Dynamische Erstellung von MQTT Discovery Geräten & Entitäten für LoRa-Sensoren.
startup: services
boot: auto
host_network: true
arch:
  - amd64
  - aarch64
  - armv7

overview: |
  Erzeugt automatisch Home Assistant Geräte & Entitäten aus beliebigen JSON MQTT Nachrichten
  (z.B. IoTree/LoRa). Analysiert dynamisch die Payload und publiziert MQTT Discovery.

discovery: []
init: false

options:
  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_user: mqtt
  mqtt_password: mqtt
  topic_prefix: physec/iotree-magdeburg-city-com/
  debounce_ms: 500
  exclude_keys:
    - firmwareVersion
    - alarmPayload

schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  topic_prefix: str
  debounce_ms: int
  exclude_keys:
    - str
